#!/bin/bash
# ====================================================================
#
# bash_unix_sv
#
# Copyright (c) 2000 Christopher M. Fuhrman
# All rights reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the Simplified BSD License (also
# known as the "2-Clause License" or "FreeBSD License".)
#
# Created Sat Nov 11 16:07:11 2000 UTC
#
# ====================================================================

#
# Sets up system environment specific to generic System 5 UNIX
# systems (e.g. UnixWARE).  Note that this is the default file if we
# cannot determine the host operating system.
#

# Try to overcome limitations of UnixWARE
stty intr ^C

# Directories to evaluate for adding to PATH
PATHS=('/usr/local/bin'                         \
       '/usr/ccs/bin'                           \
       '/usr/sfw/bin'                           \
       '/opt/sfw/bin'                           \
       '/usr/dt/bin'                            \
       '/opt/csw/sbin'                          \
       '/opt/csw/bin'                           \
       '/usr/X11/bin'                           \
       '/usr/java/bin'                          \
       '/usr/X/bin'
      )

# Pre-pend additional directories if required
for path in ${PATHS[@]}; do
        if [ -d $path ] && ! [[ "$PATH" =~ (^|:)"${path}"(:|$) ]]; then
                PATH=${path}:$PATH
        fi
done

PATH=${PATH#:}                 # Get rid of pre-pended colons
PATH=${PATH//::/:}             # Remove double colons

export PATH

# Set up alias to go to Windows home directory
if [ -n ${USERPROFILE} ]; then
        alias cdwh="cd ${USERPROFILE//\\/\\\\}"
fi

# See if coreutils is installed
aliasCoreUtils

if [[ ${OSTYPE} == 'SunOS' ]]; then
        # Make sure we have all necessary libraries loaded
        if [ -d /opt/csw/lib ]; then
                export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/csw/lib
        fi

        # Use groff for man page formatting if it's available
        if type -p groff; then
                alias man='GROFF_NO_SGR= TCAT="less -s" TROFF="groff -Tascii" man -t'
        fi

        # Use GNU AWK whenever possible
        if [ -e /opt/csw/bin/gawk ]; then
                AWK=gawk
        fi

        # Set up default ulimit
        ulimit -c unlimited
else
        export FILE_OPS_RM_FLAGS='e' # Deprecated
fi

# bash_unix_sv ends here
