#!/bin/bash
# ====================================================================
#
# bash_linux
# 
# Copyright (c) 2000 Christopher M. Fuhrman
# All rights reserved.
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the Simplified BSD License (also
# known as the "2-Clause License" or "FreeBSD License".)
#
# Created Sat Nov 11 16:07:11 2000 UTC
#
# ====================================================================

#
# Sets up system environment for Linux-based boxen
#


# This is in case we're not a login shell
if [ "x$SHLVL" != 'x1' ] && [ -e '/etc/profile.d' ]; then
        # Red Hat/Fedora Core distributions use /etc/profile.d
        for i in /etc/profile.d/*.sh; do
                if [ -x $i ]; then
                        source $i
                fi
        done
fi

# Directories to evaluate for adding to PATH
PATHS=('/snap/bin'                              \
       '/usr/games'                             \
       '/opt/schily/bin'       
      )

# Append additional directories if required
for path in ${PATHS[@]}; do
        if [ -d $path ] && ! [[ "$PATH" =~ (^|:)"${path}"(:|$) ]]; then
                PATH=$PATH:${path}
        fi
done

PATH=${PATH#:}                 # Get rid of pre-pended colons
PATH=${PATH//::/:}             # Remove double colons

# Public: Specify location of mail spool under Linux
MAIL=/var/spool/mail/$LOGNAME

export MAIL PATH

# Set WINHOME if it is present.  Note that this block of code assumes
# that the UNIX username is the same as the Windows username
if [ -d /mnt/c/Users/${USER} ]; then
        export WINHOME=/mnt/c/Users/${USER}
else
        export WINHOME=
fi

# Set up alias to go to Windows home directory
if [ ${#WINHOME} -gt 0 ]; then
        alias cdwh="cd ${WINHOME//\\/\\\\}"
fi

# Most, if not all, Linux distributions use GNU ls(1) which supports
# color terminals.  Enable color highlighting if this isn't a dumb
# terminal
if [ $TERM != 'dumb' ] && [ $TERM != 'emacs' ]; then
        alias ls='ls --color'
fi

# Public: Set up colors for ip(8)
export COLORFGBG=";0"

# Make sure dotnet programs know where it is installed
if [ -d /usr/share/dotnet ]; then
        export DOTNET_ROOT=/usr/share/dotnet
fi

# bash_linux ends here
