#!/bin/bash
# ====================================================================
#
# bash_bsd
#
# Copyright (c) 2001 Christopher M. Fuhrman
# All rights reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the Simplified BSD License (also
# known as the "2-Clause License" or "FreeBSD License".)
#
# Created Sat Jul  7 01:10:11 2001 UTC
#
# ====================================================================

#
# Sets up system environment for BSD-flavored boxen
#

# Private: Set default locale
MYLOCALE=en_US.UTF-8

# Directories to evaluate for adding to PATH
PATHS=('/usr/games'                             \
       '/usr/pkg/sbin'                          \
       '/usr/pkg/lib/perl5/site_perl/bin'
      )

# Append additional directories if required
for path in ${PATHS[@]}; do

        if [ -d $path ]; then
                echo $PATH | egrep '(^|\:)'${path}'(\:|$)' >/dev/null 2>&1 || PATH=$PATH:${path}
        fi

done

PATH=${PATH#:}			# Get rid of pre-pended colons
PATH=${PATH//::/:}		# Remove double colons

export PATH

# We want to use xterm-color under NetBSD
if [[ ${OSTYPE} == 'NetBSD' ]]; then

        NBSD_VERSION=( ${OSVERSION//./ } )

        if [[ ${NBSD_VERSION[0]} -lt 6 ]]; then

                # Reset terminal to xterm-color
                if [[ ${TERM} =~ ^xterm\-[2-9]+color ]]; then
                        echo "Resetting TERM to xterm-color"
                        TERM='xterm-color'
                        export TERM
                fi

        elif [[ -e /usr/pkg/bin/tmux ]]; then
                alias tmux='/usr/pkg/bin/tmux'
        fi

fi

# Set locale and file operation verbose flags
if [[ ${OSTYPE} != 'OpenBSD' ]]; then

        LANG=${MYLOCALE}

        # NetBSD has limited locale support
        if [[ ${OSTYPE} == 'NetBSD' ]]; then
                LC_COLLATE='C'
                LC_MONETARY='C'
                LC_NUMERIC='C'
                LC_ALL=""
        else
                LC_ALL=${MYLOCALE}
        fi

        export LANG                             \
               LC_COLLATE                       \
               LC_MONETARY                      \
               LC_NUMERIC                       \
               LC_ALL

fi

# See if coreutils is installed
aliasCoreUtils

# bash_bsd ends here
