#!/bin/bash
# ====================================================================
#
# bash_bsd
#
# Copyright (c) 2001 Christopher M. Fuhrman
# All rights reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the Simplified BSD License (also
# known as the "2-Clause License" or "FreeBSD License".)
#
# Created Sat Jul  7 01:10:11 2001 UTC
#
# ====================================================================

#
# Sets up system environment for BSD-flavored boxen
#

# Private: Set default locale
MYLOCALE=en_US.UTF-8

# Directories to evaluate for adding to PATH
PATHS=('/usr/games'                             \
       '/usr/pkg/sbin'                          \
       '/usr/pkg/lib/perl5/site_perl/bin'
      )

# Append additional directories if required
for path in ${PATHS[@]}; do

        if [ -d $path ]; then
                echo $PATH | egrep '(^|\:)'${path}'(\:|$)' >/dev/null 2>&1 || PATH=$PATH:${path}
        fi

done

PATH=${PATH#:}			# Get rid of pre-pended colons
PATH=${PATH//::/:}		# Remove double colons

export PATH

# Set LANG & LC_ALL variables
#
# NOTE: Locale-related environment variables are ignored under the
#       OpenBSD base system, so this is unlikely to have any effect
LANG=${MYLOCALE}
LC_ALL=${MYLOCALE}

export LANG                                     \
       LC_ALL

# Use GNU coreutils if available
aliasCoreUtils

# Assume we are using a 256-color screen session
if [ "$TERM" == 'screen' ]; then
        export TERM=screen-256color
fi

# bash_bsd ends here
