#!/bin/bash
# ====================================================================
#
# bash_linux
# 
# Copyright (c) 2000 Christopher M. Fuhrman
# All rights reserved.
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the Simplified BSD License (also
# known as the "2-Clause License" or "FreeBSD License".)
#
# ====================================================================

#
# Sets up system environment for Linux-based boxen
#


# This is in case we're not a login shell
if [ "x$SHLVL" != 'x1' ] && [ -e '/etc/profile.d' ]; then

        # Red Hat/Fedora Core distributions use /etc/profile.d
        for i in /etc/profile.d/*.sh; do

                if [ -x $i ]; then
                        source $i
                fi

        done

fi

# Determine PATH
paths=( '/usr/games' )

# Append additional directories if required
for path in ${paths[@]}; do

        # We only want to add the directory if it exists
        if [ -d $path ]; then
                echo $PATH | egrep '(^|\:)'${path}'(\:|$)' >/dev/null 2>&1 || PATH=$PATH:${path}
        fi

done

# Get rid of pre-pended ':' and double colons
PATH=${PATH#:}
PATH=${PATH//::/:}

# Linux distros tend to put the mail spool in a slightly different
# location
MAIL=/var/spool/mail/$LOGNAME

export MAIL PATH

# Set file operation verbose flags
export FILE_OPS_FLAGS='v'
export FILE_OPS_RM_FLAGS=${FILE_OPS_FLAGS}

# Older versions of RedHat do not support screen-256color, so reset TERM if
# necessary
if [[ $TERM =~ ^screen\-256color && -f /etc/redhat-release ]]; then

        # Grab version
        if grep ^CentOS /etc/redhat-release >/dev/null; then
                REDHAT_VERSION=$( awk '{ print $3 }' /etc/redhat-release | awk -F\. '{ print $1 }' )
        else
                REDHAT_VERSION=$( awk '{ print $7 }' /etc/redhat-release | awk -F\. '{ print $1 }' )
        fi

        if [[ ${REDHAT_VERSION} -lt 6 ]]; then
                echo 'Resetting TERM to screen'
                TERM='screen'
                export TERM
        fi

fi

# Most, if not all, Linux distributions use GNU ls(1) which supports
# color terminals.  Enable color highlighting if this isn't a dumb
# terminal
if [ $TERM != 'dumb' ] && [ $TERM != 'emacs' ]; then
        alias ls='ls --color'
fi

# Set up default ulimit
ulimit -c unlimited

# bash_linux ends here
