#!/bin/bash
# ====================================================================
#
# prompts
#
# Copyright (c) 2006, Christopher M. Fuhrman
# All rights reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the Simplified BSD License (also
# known as the "2-Clause License" or "FreeBSD License".)
#
# ====================================================================

#
# Contains functions for setting the command prompt
#
# You may add your own prompt settings as a separate function to this
# file.
#

# COLOR DEFINITIONS
BLACK_BACKGROUND='\[\033[0;40m\]'
BRIGHT_BLUE='\[\033[1;34m\]'
BRIGHT_RED='\[\033[1;31m\]'
BRIGHT_GREEN='\[\033[1;32m\]'
BRIGHT_YELLOW='\[\033[1;33m\]'
BRIGHT_CYAN='\[\033[1;36m\]'
BRIGHT_WHITE='\[\033[1;37m\]'
NO_COLOR='\[\033[0m\]'
RED='\[\033[0;31m\]'
GREEN='\[\033[0;32m\]'
YELLOW='\[\033[0;33m\]'
BLUE='\[\033[0;34m\]'
PURPLE='\[\033[0;35m\]'
WHITE='\[\033[0;37m\]'
CYAN='\[\033[0;36m\]'
LIGHT_BLUE='\033[38;5;104m\]'
LIGHT_YELLOW='\[\033[38;5;228m\]'

# Make sure GNU echo is used (especially under Solaris!)
if [ -e /usr/gnu/bin/echo ]; then
        ECHO='/usr/gnu/bin/echo'
else
        ECHO='echo'
fi

# Default prompt
DEFAULTPS1=

# Make sure GNU echo is used (especially under Solaris!)
if [ -e /usr/gnu/bin/echo ]; then
        ECHO="/usr/gnu/bin/echo"
else
        ECHO="echo"
fi

# Function: doXTerm()
#
# Sets the title font if an xterm is detected

doXTerm ()
{

        case $TERM in

        xterm*|rxvt*)
                PROMPT_COMMAND='${ECHO} -ne "\033]0;${LOGNAME}@${HOSTNAME}: ${PWD}\007"'
                ;;
        *)
                ;;

        esac

}                                                 # doXTerm()

# Function: promptCMF()
#
# Sets up prompt to my own preference

promptCMF ()
{
        doXTerm
        DEFAULTPS1=$PS1
        PS1=${BLACK_BACKGROUND}${BRIGHT_BLUE}'[ '${BRIGHT_YELLOW}'\h'${BRIGHT_BLUE}'-'${BRIGHT_WHITE}'\@'${BRIGHT_BLUE}' ]-'${BRIGHT_YELLOW}'\W '${CYAN}'$(__git_ps1 "(%s) ")'${BLACK_BACKGROUND}${BRIGHT_WHITE}'\$'${NO_COLOR}' '
        PS2='> '
        PS4='+ '

        export DEFAULTPS1
}                                                 # promptCMF()

# Function: promptCMF256()
#
# Sets up prompt using 256 colors

promptCMF256 ()
{
	doXTerm
	DEFAULTPS1=$PS1
	PS1=${BLACK_BACKGROUND}${LIGHT_BLUE}'[ '${LIGHT_YELLOW}'\h'${LIGHT_BLUE}'-'${BRIGHT_WHITE}'\@'${LIGHT_BLUE}' ]-'${LIGHT_YELLOW}'\W '${CYAN}'$(__git_ps1 "(%s) ")'${BLACK_BACKGROUND}${BRIGHT_WHITE}'\$'${NO_COLOR}' '
}

# Function: promptDefault
#
# Method that uses whatever default prompt is used by the
# current system

promptDefault ()
{
        # Only reset PS1 if there is a stored default
        if [ ${#DEFAULTPS1} -gt 0 ]; then
                PS1=$DEFAULTPS1
        else
                DEFAULTPS1=$PS1
        fi
}

# Function: promptDumb
#
# For dumb terminals

promptDumb ()
{
        doXTerm
        DEFAULTPS1=$PS1
        PS1='[ \h-\@ ]-\W $(__git_ps1 "(%s) ")\$ '
        PS2='> '
        PS4='+ '

        export DEFAULTPS1
}                                                 # promptDumb()

# Function: promptGENTOO
#
# For fans of Gentoo Linux

promptGENTOO ()
{
        doXTerm
        DEFAULTPS1=$PS1
        PS1=${BRIGHT_GREEN}'\u'@'\h'${BRIGHT_BLUE}' \w '${YELLOW}'$(__git_ps1 "(%s) ")'${BRIGHT_BLUE}'\$'${NO_COLOR}' '
        PS2="\h> "

        export DEFAULTPS1
}                                                 # promptGENTOO()

# Function: promptRED
#
# Sets up a font with reddish colors

promptRED ()
{
        doXTerm
        DEFAULTPS1=$PS1
        PS1=${BLUE}'['${RED}'\@'${BLUE}'||'${BRIGHT_RED}'\u@\h:\w'${BRIGHT_YELLOW}'$(__git_ps1 " (%s)")'${BLUE}']'${BRIGHT_WHITE}'\$ '${NO_COLOR}
        PS2='> '
        PS4='+ '

        export DEFAULTPS1
}                                                 # promptRED()

# Function: promptTFCC()
#
# A generic TFCC prompt

promptTFCC ()
{
        DEFAULTPS1=$PS1
        PS1='[\h-\[\e[32m\]\u\[\e[0m\]]$ '
        PS2='\h> '

        export DEFAULTPS1
}                                                 # promptTFCC()

# Ende
