#!/bin/bash
# ====================================================================
#
# prompts
#
# Copyright (c) 2006, Christopher M. Fuhrman
# All rights reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the Simplified BSD License (also
# known as the "2-Clause License" or "FreeBSD License".)
#
# ====================================================================

#
# Contains functions for setting the command prompt
#
# You may add your own prompt settings as a separate function to this
# file.
#

BLACK_BACKGROUND='\[\033[0;40m\]'
BRIGHT_BLUE='\[\033[1;34m\]'
BRIGHT_RED='\[\033[1;31m\]'
BRIGHT_GREEN='\[\033[1;32m\]'
BRIGHT_PURPLE='\[\033[1;35m\]'
BRIGHT_YELLOW='\[\033[1;33m\]'
BRIGHT_CYAN='\[\033[1;36m\]'
BRIGHT_WHITE='\[\033[1;37m\]'
NO_COLOR='\[\033[0m\]'
RED='\[\033[0;31m\]'
GREEN='\[\033[0;32m\]'
YELLOW='\[\033[0;33m\]'
BLUE='\[\033[0;34m\]'
PURPLE='\[\033[0;35m\]'
WHITE='\[\033[0;37m\]'
CYAN='\[\033[0;36m\]'
LIGHT_BLUE='\033[38;5;104m\]'
LIGHT_YELLOW='\[\033[38;5;228m\]'

# Public: Default prompt
DEFAULTPS1=

# Make sure GNU echo is used (especially under Solaris!)
if [ -e /usr/gnu/bin/echo ]; then
        ECHO="/usr/gnu/bin/echo"
else
        ECHO="echo"
fi

# Private: Sets the title font if an xterm is detected
#
# WARN: DO NOT unset this function as it will break other methods in
# this file.
setPromptCommand ()
{
        case $TERM in

        xterm*|rxvt*)
                PROMPT_COMMAND='${ECHO} -ne "\033]0;${LOGNAME}@${HOSTNAME}: ${PWD}\007"'
                ;;
        *)
                ;;

        esac
}

# Public: Sets up prompt to my own preference
promptCMF ()
{
        setPromptCommand
        DEFAULTPS1=$PS1
        PS1=${BLACK_BACKGROUND}${BRIGHT_BLUE}'[ '${BRIGHT_YELLOW}'\h'${BRIGHT_BLUE}'-'${BRIGHT_WHITE}'\@'${BRIGHT_BLUE}' ]-'${BRIGHT_YELLOW}'\W '${CYAN}'$(__git_ps1 "(%s) ")'${BLACK_BACKGROUND}${BRIGHT_WHITE}'\$'${NO_COLOR}' '
        PS2='> '
        PS4='+ '

        export DEFAULTPS1
}

# Public: Sets up prompt using 256 colors
promptCMF256 ()
{
        setPromptCommand
        DEFAULTPS1=$PS1
        PS1=${BLACK_BACKGROUND}${LIGHT_BLUE}'[ '${LIGHT_YELLOW}'\h'${LIGHT_BLUE}'-'${BRIGHT_WHITE}'\@'${LIGHT_BLUE}' ]-'${LIGHT_YELLOW}'\W '${CYAN}'$(__git_ps1 "(%s) ")'${BLACK_BACKGROUND}${BRIGHT_WHITE}'\$'${NO_COLOR}' '
}

# Public: Method that uses whatever default prompt is used by the
# current system
promptDefault ()
{
        # Only reset PS1 if there is a stored default
        if [ ${#DEFAULTPS1} -gt 0 ]; then
                PS1=$DEFAULTPS1
        else
                DEFAULTPS1=$PS1
        fi
}

# Public: Prompt suitable for dumb terminals
promptDumb ()
{
        setPromptCommand
        DEFAULTPS1=$PS1
        PS1='[ \h-\@ ]-\W $(__git_ps1 "(%s) ")\$ '
        PS2='> '
        PS4='+ '

        export DEFAULTPS1
}

# Public: Prompt familiar to fans of Gentoo Linux
promptGENTOO ()
{
        setPromptCommand
        DEFAULTPS1=$PS1
        PS1=${BRIGHT_GREEN}'\u'@'\h'${BRIGHT_BLUE}' \w '${YELLOW}'$(__git_ps1 "(%s) ")'${BRIGHT_BLUE}'\$'${NO_COLOR}' '
        PS2="\h> "

        export DEFAULTPS1
}

# Public: Sets up a prompt with greenish-ish colors
promptGREEN ()
{
        setPromptCommand
        DEFAULTPS1=$PS1
        PS1=${BRIGHT_BLUE}'[ '${BRIGHT_GREEN}'\h'${BRIGHT_BLUE}'-'${BRIGHT_WHITE}'\@'${BRIGHT_BLUE}' ]-'${BRIGHT_PURPLE}'\w '${CYAN}'$(__git_ps1 "(%s) ")'${BRIGHT_WHITE}'\$'${NO_COLOR}' '
        PS2='> '
        PS4='+ '

        export DEFAULTPS1
}

# Public: Sets up a prompt with reddish colors
promptRED ()
{
        setPromptCommand
        DEFAULTPS1=$PS1
        PS1=${BLUE}'['${RED}'\@'${BLUE}'||'${BRIGHT_RED}'\u@\h:\w'${BRIGHT_YELLOW}'$(__git_ps1 " (%s)")'${BLUE}']'${BRIGHT_WHITE}'\$ '${NO_COLOR}
        PS2='> '
        PS4='+ '

        export DEFAULTPS1
}

# Public: Prompt used at a former employer
promptTFCC ()
{
        DEFAULTPS1=$PS1
        PS1='[\h-\[\e[32m\]\u\[\e[0m\]]$ '
        PS2='\h> '

        export DEFAULTPS1
}

# prompts ends here
