#!/bin/bash
# ====================================================================
#
# prompts
# 
# Author:: Christopher M. Fuhrman <cfuhrman@pobox.com>
# Copyright:: Copyright (c) 2006, Christopher M. Fuhrman
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
# 
#    1. Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
# 
#    2. Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY CHRISTOPHER M. FUHRMAN ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL CHRISTOPHER
# M. FUHRMAN OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
# 
# The views and conclusions contained in the software and
# documentation are those of the authors and should not be interpreted
# as representing official policies, either expressed or implied, of
# Christopher M. Fuhrman.
# 
# DESCRIPTION:
#
#   Contains functions for setting the command prompt
#
# Usage:
#
#   bash source prompts
#
# You may add your own prompt settings as a separate function to this
# file.
#
# ====================================================================

# COLOR DEFINITIONS
BLACK_BACKGROUND='\[\033[0;40m\]'
BRIGHT_BLUE='\[\033[1;34m\]'
BRIGHT_RED='\[\033[1;31m\]'
BRIGHT_GREEN='\[\033[1;32m\]'
BRIGHT_YELLOW='\[\033[1;33m\]'
BRIGHT_CYAN='\[\033[1;36m\]'
BRIGHT_WHITE='\[\033[1;37m\]'
NO_COLOR='\[\033[0m\]'
RED='\[\033[0;31m\]'
GREEN='\[\033[0;32m\]'
YELLOW='\[\033[0;33m\]'
BLUE='\[\033[0;34m\]'
PURPLE='\[\033[0;35m\]'
WHITE='\[\033[0;37m\]'
CYAN='\[\033[0;36m\]'

# Make sure GNU echo is used (especially under Solaris!)
if [ -e /usr/gnu/bin/echo ]; then
        ECHO='/usr/gnu/bin/echo'
else
        ECHO='echo'
fi

# Function: doXTerm()
#
# Sets the title font if an xterm is detected

doXTerm ()
{

        case $TERM in

        xterm*|rxvt*)
                PROMPT_COMMAND='${ECHO} -ne "\033]0;${LOGNAME}@${HOSTNAME}: ${PWD}\007"'
                ;;
        *)
                ;;

        esac

}                                                 # doXTerm()

# Function: promptCMF()
#
# Sets up prompt to my own preference

promptCMF ()
{
        doXTerm
        PS1=${BLACK_BACKGROUND}${BRIGHT_BLUE}'[ '${BRIGHT_YELLOW}'\h'${BRIGHT_BLUE}'-'${BRIGHT_WHITE}'\@'${BRIGHT_BLUE}' ]-'${BRIGHT_YELLOW}'\W '${CYAN}'$(__git_ps1 "(%s) ")'${BLACK_BACKGROUND}${BRIGHT_WHITE}'\$'${NO_COLOR}' '
        PS2='> '
        PS4='+ '
}                                                 # promptCMF()

# Function: promptDumb
#
# For dumb terminals

promptDumb ()
{
        doXTerm
        PS1='[ \h-\@ ]-\W $(__git_ps1 "(%s) ")\$ '
        PS2='> '
        PS4='+ '
}                                                 # promptDumb()

# Function: promptGENTOO
#
# For fans of Gentoo Linux

promptGENTOO ()
{
        doXTerm
        PS1=${BRIGHT_GREEN}'\u'@'\h'${BRIGHT_BLUE}' \w '${YELLOW}'$(__git_ps1 "(%s) ")'${BRIGHT_BLUE}'\$'${NO_COLOR}' '
        PS2="\h> "
}                                                 # promptGENTOO()

# Function: promptRED
#
# Sets up a font with reddish colors

promptRED ()
{
        doXTerm
        PS1=${BLUE}'['${RED}'\@'${BLUE}'||'${BRIGHT_RED}'\u@\h:\w'${BRIGHT_YELLOW}'$(__git_ps1 " (%s)")'${BLUE}']'${BRIGHT_WHITE}'\$ '${NO_COLOR}
        PS2='> '
        PS4='+ '

}                                                 # promptRED()

# Function: promptTFCC()
#
# A generic TFCC prompt

promptTFCC ()
{
        PS1='[\h-\[\e[32m\]\u\[\e[0m\]]$ '
        PS2='\h> '
}                                                 # promptTFCC()

# Ende
