#+TITLE: GNU Emacs Requirements & Installation
#+AUTHOR: Christopher M. Fuhrman
#+EMAIL: cfuhrman@pobox.com
#+OPTIONS: email:t
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \pagestyle{fancyplain}
#+LATEX_HEADER: \usepackage{bookmark}
#+LATEX_HEADER: \hypersetup{urlcolor=blue}
#+LATEX_HEADER: \hypersetup{colorlinks,urlcolor=blue}
#+LATEX_HEADER: \fancyhead[RE,LO]{\leftmark}
#+LATEX_HEADER: \fancyhead[LE,RO]{\thepage}

#+LATEX: \thispagestyle{empty}

* Overview

  Provides information about the care and feeding of this GNU Emacs
  configuration.

* Requirements

** Operating System Requirements

   This configuration is compatible with GNU Emacs 28.1 or greater and has been
   tested under various Linux distributions, Windows 11 and NetBSD.  As I no
   longer use a Mac on a regular basis, no testing was done under that
   environment.

   This configuration is *not* compatible with XEmacs.

** Font requirements

   The following fonts are utilized when running Emacs in a window system
   environment:

     - [[https://fonts.google.com/specimen/Cantarell][Cantarell]]
     - [[https://github.com/tonsky/FiraCode][Fira Code]]
     - [[https://www.jetbrains.com/lp/mono/][JetBrains Mono]]

   In order to support emoji as well as custom icons, consider installing the
   following fonts:

     - OpenSymbol
     - Symbola

   In most cases, these can be installed via the package manager (apt, brew,
   dnf, pkg, zypper, etc.,) of your operating system.

* Getting the source

  The master repository is managed by the [[https://fossil-scm.org][Fossil]] distributed version control
  system.  To check out the repository:

  # DONT: Change these URLs to use the public repository in the public branch!
  #+begin_src sh
    # Clone the repository.  Note the destination directory is up to you.
    fossil clone https://fossil.fuhrwerks.com/shpak ~/shpak.fsl

    # Check out the repository
    mkdir shellpak # Or whatever name you want to call it
    cd shellpak
    fossil open ~/shpak.fsl 
  #+end_src

** Git

   An export of the Fossil repository is available on GitHub.  To check out this
   repository, do the following:

   # DONT: Be sure to change URL in public branch
   #+begin_src sh
     # Clone the repository
     git clone https://github.com/cfuhrman/shellpak
   #+end_src

* Installation

  Emacs can be installed by the included =setup.sh= script located at the
  top-level directory.  Note this requires the =bash= shell.

  #+begin_src sh
    # This will /only/ install emacs configuration files
    ./setup.sh -e

    # Display command line options
    ./setup.sh -h
  #+end_src

* Organization

  This GNU Emacs configuration has been broken up into the following modules.
  An attempt has been made to break up functionality into sections I consider
  logical although opinions differ.  If you have strong opinions about how
  things should be organized, feel free to fork this project and organize it to
  your heart's content.

** cmf-appearance.el

   This file contains aspects that control the appearance of Emacs.  This
   includes color theming and Modeline configuration in addition to customizing
   the use of icons.  If a package or customization stanza controls how Emacs
   /looks/, then it goes in this file.

*** Specific customizations

    * Theme :: [[https://github.com/clearfeld/vscode-theme-doom-sourcerer][Doom Sourcerer]]
    * Modeline :: [[https://github.com/seagle0128/doom-modeline][Doom Modeline]]
    * Font (Main) :: [[https://www.jetbrains.com/lp/mono/][JetBrains Mono]]

** cmf-enhancements

   This is functionality that /enhances/ GNU Emacs by adding new features.
   This section includes Macros, custom keybindings, mode customization as well
   as the addition of packages that add functionality.  Notable packages
   include:

    * [[https://github.com/karthink/gptel][gptel]]
    * [[https://codeberg.org/martianh/mastodon.el][mastodon]]
    * [[https://github.com/pashky/restclient.el][restclient]]

** cmf-file-support

   This is for adding support for specific files that are not otherwise
   addressed by [[*cmf-programming][cmf-programming]].  Generally speaking, if the file type isn't
   related to a specific programming language, it is addressed here.  Most
   notable additions are:

    * [[https://github.com/emacs-php/apache-mode][apache-mode]]
    * [[https://github.com/spotify/dockerfile-mode][dockerfile-mode]]
    * [[https://github.com/json-emacs/json-mode][json-mode]]
    * [[https://github.com/yoshiki/yaml-mode][yaml-mode]]

** cmf-ide

   This file contains settings and packages that turn Emacs into a modern,
   powerful IDE on par with VS Code and the JetBrains family of products.  In my
   mind, an IDE includes the ability to work with more than just programming
   languages, so this file contains support for features also useful for
   authoring and publishing.

*** Notable packages

    This list is /not/ comprehensive.

     * [[https://github.com/emacs-lsp/dap-mode][dap-mode]] :: For debugging
     * [[https://www.flycheck.org/en/latest/][flycheck]] :: On-the-fly syntax checking
     * [[https://emacs-lsp.github.io/lsp-mode/][lsp-mode]] :: Language Server Protocol client providing IntelliSense-like
       functionality
     * [[https://magit.vc/][Magit]] :: Git porcelain for Emacs
     * [[https://projectile.mx/][Projectile]] :: Project interaction library
     * [[https://github.com/Alexander-Miller/treemacs][Treemacs]] :: A tree-layout file explorer
     * [[https://tumbleweed.nu/r/vc-fossil/doc/tip/README.md][vc-fossil]] :: Support for the [[https://fossil-scm.org][Fossil]] distributed SCM
     * [[https://github.com/joaotavora/yasnippet][YASnippet]] :: A template system

** cmf-org

   My personal [[https://orgmode.org/][org-mode]] configuration.

** cmf-programming

   This file includes support for a large number of programming languages
   including PHP, C#, Perl, Python and GoLang.

** cmf-publishing

   This file contains support for publishing/authoring environments including
   markdown and LaTeX.

** cmf-ui

   User interface enhancements, including packages for Window navigation and
   text completion.  Notable packages include:

    * [[https://company-mode.github.io/][company-mode]] :: Text-completion mode
    * [[https://github.com/abo-abo/swiper][Ivy]] :: A generic completion framework that includes replacements for
      common Emacs commands

* Resources

   - [[https://www.gnu.org/software/emacs/manual/][GNU Emacs Manual]]
   - [[https://www.emacswiki.org/emacs/SiteMap][Emacs Wiki]]
   - [[https://www.youtube.com/@SystemCrafters/featured][System Crafters Youtube Channel]] (Contains lots of great videos on
     configuring and using Emacs!)

* Copyright

  Copyright (c) 2000-2026 Christopher M. Fuhrman \\
  All rights reserved. \\

  All files contained herein can be redistributed and/or modified   \\
  under the terms of the Simplified BSD License (also known as the  \\
  "2-Clause License" or "FreeBSD License".) unless otherwise noted.

