#
# docs/GNUmakefile
#
# Created Wed Oct  9 17:22:38 2013 UTC
#

# Files
ORG_FILES=README.org
ORG_FILES+=EMACS-REWRITE-2021.org
ORG_FILES+=EMACS-REWRITE-2024.org
ORG_FILES+=EMACS-UNDER-MSWIN.org

include ../mk/documentation.mk

# docs/GNUmakefile ends here
