#+TITLE: ShellPAK README
#+AUTHOR: Christopher M. Fuhrman
#+EMAIL: cfuhrman@pobox.com
#+OPTIONS: email:t
#
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \pagestyle{fancyplain}

#+LATEX: \thispagestyle{empty}
# [TABLE-OF-CONTENTS]

* Overview

  Provides a general overview of ShellPAK as well as instructions for
  installing and removing ShellPAK.

* Description

  ShellPAK allows for the automatic installation and configuration of
  my personal [[http://www.gnu.org/software/bash/][GNU Bash]] shell environment as well as the configuration
  of the following programs:

   - [[http://git-scm.com][Git]]
   - [[http://www.gnu.org/software/emacs/][GNU Emacs]]
   - [[http://www.gnu.org/software/screen/][GNU Screen]]
   - [[https://www.gnu.org/software/indent/][GNU Indent]]
   - [[http://search.cpan.org/~shancock/Perl-Tidy-20140711/lib/Perl/Tidy.pod][Perl::Tidy]]
   - [[http://tmux.sourceforge.net][tmux]]

** Requirements

    - GNU Bash version 3.2 or greater
    - GNU Emacs 23.1 or greater (Emacs >24.1 preferred)
    - rsync

** Supported Platforms

   The following operating systems are known to be supported:

    - Mac OS X 10.9 (Darwin)
    - NetBSD 6.1.x
    - OpenBSD 5.4
    - CentOS 6.5
    - Debian 7 (Wheezy) and derivatives
    - SunOS solaris 5.10
    - AIX 1 7

   In addition, ShellPAK has been known to run on OpenSuSE, SuSE
   Enterprise Linux, Ubuntu, FreeBSD, and Cygwin.

* Obtaining ShellPAK

  As of <2014-07-30 Wed>, [[https://chiselapp.com/user/cfuhrman/repository/shpak/home][ShellPAK]] is managed by the [[http://fossil-scm.org][Fossil]]
  distributed version control system.  To check out a repository:

  #+begin_src sh
  # Clone the repository
  $ fossil clone https://chiselapp.com/user/cfuhrman/repository/shpak ~/shellpak.fossil

  # Check out the repository
  $ mkdir shellpak
  $ cd shellpak
  $ fossil open ~/shellpak.fossil
  #+end_src

  Further information on Fossil can be found at this [[http://www.fossil-scm.org/index.html/doc/trunk/www/quickstart.wiki][Quick Start
  Guide]].

** Alternate Repositories

   [[https://chiselapp.com/user/cfuhrman/repository/shpak/home][ShellPAK]] is also available for checkout from the following
   locations:

    - Git :: [[https://github.com/cfuhrman/shpak][GitHub]], [[https://bitbucket.org/chrisfuhrman/shellpak][BitBucket]]
    - Fossil :: [[https://www.fuhrwerks.com/fossil/shpak][FuhrWerks]]
    - Bazaar :: [[https://code.launchpad.net/~cfuhrman/shpak/trunk][Launchpad]]

   Be aware that portions of the ShellPAK infrastructure relies on
   Fossil.  Conversion to support the conventions of an alternative
   revision control system is an exercise left to the user.

* Installation

  #+begin_src sh
  # Install ShellPAK
  $ ./setup.sh
  #+end_src

  Note that during installation, ShellPAK will store dot-files (e.g.,
  =bashrc=, =bash_profile=, etc) in =~/Backup/shell= (or whatever is
  specified by the =-b= flag).  These files will be restored during
  un-installation (via the =-u= flag)

** Other setup options

   #+begin_src sh
   # Perform a dry-run
   $ ./setup.sh -r

   # Install into another directory
   $ ./setup.sh -d /path/to/directory

   # Do not automatically link files during installation
   $ ./setup.sh -n

   # Remove ShellPAK
   $ ./setup.sh -u

   # Change backup directory
   $ ./setup.sh -b /path/to/directory

   # List runtime options
   $ ./setup.sh -h
   #+end_src


* Bugs

  Please report any bugs or feature requests by [[https://chiselapp.com/user/cfuhrman/repository/shpak/reportlist][filing a ticket]] via
  the ShellPAK repository website.

* Author

  Christopher M. Fuhrman
  [[mailto:cfuhrman@pobox.com][cfuhrman@pobox.com]]

* Copyright

  Copyright (c) 2000-2014 Christopher M. Fuhrman
  All rights reserved.

  All files contained herein can be redistributed and/or modified
  under the terms of the Simplified BSD License (also known as the
  "2-Clause License" or "FreeBSD License".) unless otherwise noted.

